CREATE TABLE IF NOT EXISTS free_form_questions (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  free_form_exercise_id bigint NOT NULL REFERENCES free_form_exercises(id) ON DELETE CASCADE,
  question text NOT NULL,
  question_order integer NOT NULL DEFAULT 1
);

CREATE TRIGGER updated_at
  BEFORE UPDATE
  ON public.free_form_questions
  FOR EACH ROW
EXECUTE FUNCTION updated_at();

ALTER TABLE free_form_answers
ADD COLUMN IF NOT EXISTS free_form_question_id BIGINT
REFERENCES free_form_questions(id) ON DELETE CASCADE;

ALTER TABLE free_form_user_answers
ADD COLUMN IF NOT EXISTS free_form_question_id BIGINT
REFERENCES free_form_questions(id) ON DELETE CASCADE;