CREATE TABLE IF NOT EXISTS fill_gap_exercises (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  exercise_id bigint NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  title text NOT NULL,
  source_text text NOT NULL,
  UNIQUE (exercise_id)
);

CREATE TABLE IF NOT EXISTS fill_gap_gaps (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  fill_gap_exercise_id bigint NOT NULL REFERENCES fill_gap_exercises(id) ON DELETE CASCADE,
  token_index integer NOT NULL,
  token_text text NOT NULL,
  gap_order integer NOT NULL,
  UNIQUE (fill_gap_exercise_id, token_index)
);

CREATE TABLE IF NOT EXISTS fill_gap_answers (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  fill_gap_gap_id bigint NOT NULL REFERENCES fill_gap_gaps(id) ON DELETE CASCADE,
  answer text NOT NULL,
  is_correct boolean NOT NULL DEFAULT false,
  feedback text NOT NULL
);

CREATE TABLE IF NOT EXISTS fill_gap_user_answers (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fill_gap_gap_id bigint NOT NULL REFERENCES fill_gap_gaps(id) ON DELETE CASCADE,
  answer text NOT NULL,
  is_correct boolean NOT NULL DEFAULT false,
  feedback text,
  UNIQUE (user_id, fill_gap_gap_id)
);